    <script
      type="text/javascript"
      src="https://cdn.usebootstrap.com/bootstrap/5.0.1/js/bootstrap.bundle.min.js"
      id="bootstrap-js"
    ></script>

    <script
      type="text/javascript"
      src="https://kit.fontawesome.com/bd74a11c46.js"
      id="wpdocs-bootstrap-bundle-script-js"
    ></script>
    <script
      async
      defer
      crossorigin="anonymous"
      src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0"
      nonce="1J8CUjA9"
    ></script>
    <script
      src="https://kit.fontawesome.com/bd74a11c46.js"
      crossorigin="anonymous"
    ></script>